// main-application/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'main-application-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less'],
})
export class AppComponent {
  title = 'angular-app';
}

<!-- <main-application-nx-welcome></main-application-nx-welcome> -->
<union-component-greeting [title]="title"></union-component-greeting>
<test-union-angular [title]="title"></test-union-angular>

// main-application/react-app/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.less';

import NxWelcome from './nx-welcome';

export function App() {
  return (
    <div>
      <union-component-greeting title="react-app" />
      <test-union-angular title="react-app" />
    </div>
  );
}

export default App;
